app = "spaceeconomy"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[http_service.checks]
  [http_service.checks.health]
    interval = "10s"
    timeout = "5s"
    grace_period = "120s"
    method = "GET"
    path = "/health"

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"

[mounts]
  source = "se_data"
  destination = "/app/data"
